[package]
name = "axplat-aarch64-bsta1000b"
version = "0.1.0"
edition.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
documentation.workspace = true
repository.workspace = true

[features]
fp_simd = ["axcpu/fp_simd"]
irq = []
rtc = []
smp = []

[dependencies]
log = "=0.4.21"
kspin = "0.1"
memory_addr = "0.3"
page_table_entry = "0.5"
dw_apb_uart = "0.1"

axconfig-macros = "0.2"
axplat-aarch64-common = { version = "0.1", path = "../axplat-aarch64-common" }
axcpu = { workspace = true }
axplat = { workspace = true }
