# Architecture identifier.
arch = "<ARCH>" # str
# Platform identifier.
platform = "<PLATFORM>" # str

#
# Platform configs
#
[plat]
# Platform family (deprecated).
family = "" # str

# Base address of the whole physical memory.
phys-memory-base = 0            # uint
# Size of the whole physical memory. (128M)
phys-memory-size = 0x800_0000   # uint
# Base physical address of the kernel image.
kernel-base-paddr = 0x20_0000   # uint
# Base virtual address of the kernel image.
kernel-base-vaddr = "0xffff_8000_0020_0000"     # uint
# Linear mapping offset, for quick conversions between physical and virtual
# addresses.
phys-virt-offset = "0xffff_8000_0000_0000"      # uint
# Offset of bus address and phys address. some boards, the bus address is
# different from the physical address.
phys-bus-offset = 0                             # uint
# Kernel address space base.
kernel-aspace-base = "0xffff_8000_0000_0000"    # uint
# Kernel address space size.
kernel-aspace-size = "0x0000_7fff_ffff_f000"    # uint

#
# Device specifications
#
[devices]
# MMIO regions with format (`base_paddr`, `size`).
mmio-regions = []           # [(uint, uint)]
# VirtIO MMIO regions with format (`base_paddr`, `size`).
virtio-mmio-regions = []    # [(uint, uint)]
# Base physical address of the PCIe ECAM space.
pci-ecam-base = 0           # uint
# End PCI bus number.
pci-bus-end = 0             # uint
# PCI device memory ranges.
pci-ranges = []             # [(uint, uint)]
