[package]
name = "axplat-example" # to be overwritten
version = "0.1.0"       # to be overwritten
edition = "2021"        # to be overwritten

[dependencies]
axconfig-macros = "0.2"
axplat = { git = "https://github.com/arceos-org/axplat_crates" }
