[package]
name = "axplat-x86-pc"
version = "0.1.0"
edition.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
documentation.workspace = true
repository.workspace = true

[features]
fp_simd = ["axhal_cpu/fp_simd"]
irq = []
rtc = ["x86_rtc"]
smp = []
reboot-on-system-off = []

[dependencies]
kspin = "0.1"
log = "=0.4.21"
bitflags = "2.6"
lazyinit = "0.2"
int_ratio = "0.1"
percpu = "0.2"
memory_addr = "0.3"
heapless = "0.8"
axconfig-gen-macros = { version = "0.1", features = ["nightly"] }
axhal_cpu = { version = "0.1.0", path = "../../axhal_cpu" }
axplat = { version = "0.1.0", path = "../../axplat" }

x86 = "0.52"
x86_64 = "0.15.2"
x2apic = "0.4"
multiboot = "0.8"
raw-cpuid = "11.1"
uart_16550 = "0.3"
x86_rtc = { version = "0.1", optional = true }
