[package]
name = "axplat-aarch64-peripherals"
version = "0.2.0"
description = "ARM64 common peripheral drivers with `axplat` compatibility"
documentation = "https://docs.rs/axplat-aarch64-peripherals"
keywords = ["arceos", "os", "hal", "peripheral", "aarch64"]
categories = ["embedded", "no-std", "hardware-support", "os"]
edition.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[dependencies]
kspin = "0.1"
log = "0.4"
spin = "0.10"
int_ratio = "0.1"
lazyinit = "0.2"
page_table_entry = "0.5"
aarch64-cpu = "10.0"
arm_pl011 = "0.1"
arm-gic-driver = "0.15"
arm_pl031 = "0.2"
axcpu = { workspace = true }
axplat = { workspace = true, features = ["irq"] }

[package.metadata.docs.rs]
targets = ["aarch64-unknown-none"]
