# Architecture identifier.
arch = "aarch64"                                # str
# Platform identifier.
platform = "aarch64-opi-aipro"                 # str
# Platform package.
package = "axplat-aarch64-opi-aipro"           # str

#
# Platform configs
#
[plat]
# Number of CPUs.
cpu-num = 1                         # uint
# Base address of the whole physical memory.
phys-memory-base = 0x0000_0000      # uint
# Size of the whole physical memory. (~2G)
phys-memory-size = 0x7800_0000      # uint
# Base physical address of the kernel image.
kernel-base-paddr = 0x2900_0000     # uint
# Base virtual address of the kernel image.
kernel-base-vaddr = "0xffff_0000_2900_0000"     # uint
# Linear mapping offset, for quick conversions between physical and virtual
# addresses.
phys-virt-offset = "0xffff_0000_0000_0000"      # uint
# Offset of bus address and phys address. some boards, the bus address is
# different from the physical address.
phys-bus-offset = 0                             # uint
# Kernel address space base.
kernel-aspace-base = "0xffff_0000_0000_0000"    # uint
# Kernel address space size.
kernel-aspace-size = "0x0000_ffff_ffff_f000"    # uint
# Stack size on bootstrapping. (256K)
boot-stack-size = 0x40000                       # uint

# PSCI
psci-method = "smc"             # str

# CPU Hardware ID list
cpu-id-list = [0x00, 0x100, 0x200, 0x300]

#
# Device specifications
#
[devices]
# MMIO ranges with format (`base_paddr`, `size`).
mmio-ranges = [
    ["0xc401_0000", "0x1000"],      # UART 0
    ["0x8223_0000", "0x1000"],      # UART 1
    ["0x4_0108_0000", "0x1000"],      # UART 2

    ["0x8_2000_0000", "0x40_0000"], # pcie ecam

    ["0x3_0017_0000", "0x10000"],      # MIO0 - I2C
    ["0x3_0018_0000", "0x10000"],      # MIO1 - I2C
    ["0x3_001a_0000", "0x10000"],      # MIO2 - I2C

    ["0xc404_0000", "0x10000"],      # GPIO0 
    ["0xc405_0000", "0x10000"],      # GPIO1 
    ["0x820f_0000", "0x10000"],      # GPIO2 
    ["0x8210_0000", "0x10000"],      # GPIO3 
    ["0xa016_0000", "0x10000"],      # GPIO4 
    ["0x3_0016_0000", "0x10000"],      # GPIO5
    ["0x4_0015_0000", "0x10000"],

    ["0xd000_0000", "0x10000"],     # gicd
    ["0xd010_0000", "0x80_0000"],   # gicr
    ["0xd200_0000", "0x10_0000"],   # gic-its

    ["0x8200_0000", "0x10000"],      # mmc
    ["0x8201_0000", "0x10000"],      # sd
  ]                               # [(uint, uint)]
# VirtIO MMIO ranges with format (`base_paddr`, `size`).
virtio-mmio-ranges = []        # [(uint, uint)]
# Base physical address of the PCIe ECAM space.
pci-ecam-base = 0x82000_0000     # uint
# End PCI bus number.
pci-bus-end = 0x2               # uint
# PCI device memory ranges.
pci-ranges = [
    [0x8_2000_0000, 0x40_0000]   
]                                       # [(uint, uint)]
# UART Address
uart-paddr = 0xc401_0000        # uint
# UART IRQ number (SPI, 0x54)
uart-irq = 0xa9                 # uint
# Timer interrupt num (PPI, physical timer).
timer-irq = 0x04                # uint
# IPI interrupt num
ipi-irq = 1                     # uint

# GIC CPU Interface base address
gicr-paddr = 0xd010_0000        # uint
# GIC Distributor base address
gicd-paddr = 0xd000_0000        # uint
