[package]
name = "axplat-aarch64-raspi"
version = "0.1.0"
description = "Implementation of `axplat` hardware abstraction layer for Raspberry Pi 4B board."
keywords = ["arceos", "os", "hal", "aarch64", "raspi"]
categories = ["embedded", "no-std", "hardware-support", "os"]
edition.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
documentation.workspace = true
repository.workspace = true

[features]
fp-simd = ["axcpu/fp-simd"]
irq = ["axplat/irq"]
rtc = [] # Not implemented, currently no effect
smp = ["axplat/smp"]

[dependencies]
log = "0.4"
aarch64-cpu = "10.0"
page_table_entry = "0.5"
axconfig-macros = "0.2"
axplat-aarch64-peripherals = { version = "0.1", path = "../axplat-aarch64-peripherals" }
axcpu = { workspace = true }
axplat = { workspace = true }
