[package]
name = "axplat-aarch64-qemu-virt"
version = "0.1.0"
edition.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
documentation.workspace = true
repository.workspace = true

[features]
fp_simd = ["axhal_cpu/fp_simd"]
irq = []
rtc = []
smp = []

[dependencies]
memory_addr = "0.3"
page_table_entry = "0.5"
axconfig-gen-macros = "0.1"
axplat-aarch64-common = { version = "0.1", path = "../axplat-aarch64-common" }
axhal_cpu = { version = "0.1", path = "../../axhal_cpu" }
axhal_plat = { version = "0.1", path = "../../axhal_plat" }
